import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// Use relative path for globals.css if possible, or ensure the absolute path is correct
// For example, if globals.css is in the app directory:
import "./globals.css";
// Or if it's in src/:
// import "@/app/globals.css"; // Assuming "@/"" maps to "src/" in tsconfig
import ClientWrapper from "@/components/ClientWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-gray-100 min-h-screen">
        <ClientWrapper>
          <main>{children}</main>
        </ClientWrapper>
      </body>
    </html>
  );
}
