import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "/Users/rodneyshen/Desktop/rod/dashboardv1/src/app/globals.css";
import Sidebar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen bg-gray-100 font-[family-name:var(--font-geist-sans)]">
        <Sidebar />
        <main className="flex-1 p-6 pl-64">{children}</main>
      </body>
    </html>
  );
}
